### ISSUE TITLE
[Feature Request] Have Argo CD to support Crossplane natively

### ISSUE THREAD

**Issue by morningspace** [crossplane-contrib/provider-argocd#10]
### What problem are you facing?

When using Argo CD with Helm in GitOps, I can customize the parameters exposed by Helm values.yaml either from Argo CD UI or command line. Essentially, it exposes helm specific options via `Application.argoproj.io` so that can override default configuration in values.yaml.

![image](https://user-images.githubusercontent.com/16119920/139620217-2f191cd6-fc3d-403e-89b3-a7111ac9cc3e.png)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: path/to/your/config
    repoURL: 'https://github.com/<account>/<repo>'
    targetRevision: HEAD
    helm:
      parameters:
        - name: path.to.foo
          value: bar
  project: default
```

Crossplane on the other hand supports defining Composition, CompositeResourceDefinition (XRD), CompositeResource (XR) and CompositeResourceClaim (XRC) which is very similar to what Helm does. These resources can be checked in git to support GitOps. Below is a table that summarizes the side-by-side comparison between Crossplane and Helm. More details can be found [here](https://github.com/morningspace/capabilities-shim-gitops/blob/main/docs/using-crossplane-in-gitops-2.md#crossplane-vs-helm).

| Crossplane                  | Helm        | Description
|:----------------------------|:------------|:-----
| Composition                 | Templates   | Both to compose a set of Kubernetes resources, but Composition uses patch to override while Helm uses template.
| CompositeResource(Claim)    | values.yaml | Both to allow user input as configurable settings. Argo CD has better support on Helm, e.g: to specify values in Argo `Application` resource.
| CompositeResourceDefinition | n/a         | CompositeResourceDefinition as a schema has better user input control.

With XRD, XR/XRC, Crossplane is more reliable  than Helm for user input as custom options. e.g.: to define a type for each option, mark it as required or optional, give it a description text, etc.

However, there is no such support as Helm does in Argo CD for UI and `Application.argoproj.io` integration.

### How could Crossplane help solve your problem?

I know it may not be a good place to raise it here. We should ask a feature request in Argo CD community since this is more on Argo CD side to address such an issue. Also, it may not be easy to implement given the Crossplane design nature from tech perspective. But before that, just to make sure if that generally makes sense from Crossplane community side.

Ideally, I would like to see Crossplane could be taken as first-class citizen in Argo CD just as Helm, Kustomize, and other tools. We can attach custom options in `Application.argoproj.io` resource to override the default settings defined by XR/XRC as below. And this can also be supported via Argo CD web UI, as Helm does.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  source:
    path: path/to/your/config
    repoURL: 'https://github.com/<account>/<repo>'
    targetRevision: HEAD
    crossplane:
      SomeXRC:
        - name: path.to.foo
          value: bar
  project: default
```

Does it make sense?
