### ISSUE TITLE
Declarative provider-argocd installation

### ISSUE THREAD

**Issue by exocode** [crossplane-contrib/provider-argocd#17]
I normally install my providers with a manifest: 

Example for Civo provider:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-civo
spec:
  package: "crossplane/provider-civo:main"
```

Now I tried that same approach with `provider-argocd`:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-46"
spec:
  package: "crossplane/provider-argocd:main" # also tried crossplane-contrib/provider-argocd:main
```

But it is not get "healthy":

<img width="727" alt="Bildschirmfoto 2022-01-25 um 11 53 19" src="https://user-images.githubusercontent.com/1597621/150963709-7fafe2de-921f-46a5-b5f8-4f026d18665f.png">

Am I using this plugin wrong?

I didn't saw the installation step in the docs.

Thank you
