### ISSUE TITLE
Connect or register Civo created cluster in ArgoCD

### ISSUE THREAD

**Issue by exocode** [crossplane-contrib/provider-argocd#18]
I have a cluster which is created by Crossplane through the Civo provider.
That process created a secret containing the `kubeconfig`. 

- **How can I register that cluster in ArgoCD automatically (GitOps)?**

Normally, I manually add the IP address to the ArgoCD `AppProject` if the cluster creation process has finished. Then I manually change all manifests which are using this server address. In an issue I raised here: https://github.com/argoproj/argo-cd/issues/8107#issuecomment-1012479197 they mentioned, that I can use a "string reference" of my cluster, (they pointed me there: https://doc.crds.dev/github.com/crossplane-contrib/provider-argocd/projects.argocd.crossplane.io/Project/v1alpha1@v0.1.0#spec-forProvider-destinations )

but I have no idea to do that. I simply didn't get it,...
 
That is my current state:

appProject
```yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
spec:
  description: staging deployment
  destinations:
    - namespace: "staging"
      name: "staging"
      server: https://123.456.789.0 # <<-- Somewhere here
      serverRef:                    # <<-- or here
        name: "staging"             # <<-- or here I can reference to my crossplane cluster by a name string, right?
```

How can I bridge the gap between my Crossplane created cluster and ArgoCD `Application` deployments without manual intervention? Isn't your repo's intention to exactly do that? I didn't found any example which makes sense for me to get that working. 

What I found is, that I can create a `secret` to register my cluster (if I am not completely misunderstand):

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: staging-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }
``` 

Am I right, that my demands are not possible to achieve automatically at the moment? If not, who is "responsible" to create that? CivoProvider? provider-argocd? argocd itself? 

**It would be awesome if someone can get me out of that configuration hell 😈**

**Comment by janwillies** [comment]
First you would create a [cluster](https://doc.crds.dev/github.com/crossplane-contrib/provider-argocd/cluster.argocd.crossplane.io/Cluster/v1alpha1@v0.1.0) in `provider-argocd`, see here for an example: https://github.com/crossplane-contrib/provider-argocd/blob/main/examples/cluster/cluster.yaml

Then you'd create a [project](https://doc.crds.dev/github.com/crossplane-contrib/provider-argocd/projects.argocd.crossplane.io/Project/v1alpha1@v0.1.0), for example: https://github.com/crossplane-contrib/provider-argocd/blob/main/examples/projects/project.yaml. Within the `project` you can [reference](https://doc.crds.dev/github.com/crossplane-contrib/provider-argocd/projects.argocd.crossplane.io/Project/v1alpha1@v0.1.0#spec-forProvider-destinations-serverRef) a `cluster` by its kubernetes resource name. You don't need to keep the URLs in sync manually, this should be done by `provider-argocd` automatically.

From what I understand `provider-civo` creates a [kubeconfig](https://github.com/crossplane-contrib/provider-civo/blob/main/internal/controller/civokubernetes/civokubernetes.go#L132) in the connection secret. This is currently not parsed by `provider-argocd`, see [#13](https://github.com/crossplane-contrib/provider-argocd/issues/13#issuecomment-1014428062)

**Comment by exocode** [comment]
> From what I understand provider-civo creates a kubeconfig in the connection secret. This is currently not parsed by provider-argocd, see #13

So me, as a Civo-provider user could ask Civo Provider maintainers, to provide a compiant ArgoCD secret? Or is this repo thinking about picking up kubeconfig 


At the moment I am trying to do something like this: (It's "grep"-ing the IP address, but I stuck at the moment connect to ArgoCD servers API)


```yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: assign-staging-ip-job
  namespace: default
  labels:
    app: assign-staging-ip-job
spec:
  template:
    metadata:
      name: assign-staging-ip-job
      labels:
        app: assign-staging-ip-job
    spec:
      serviceAccountName: secret-reader-sa
      containers:
        - name: assign-staging-ip-job
          image: alpine:latest
          command:
            - bin/sh
            - -c
            - |
              echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
              cat /etc/apk/repositories
              apk update
              apk add yq jq curl coreutils --no-cache
              export SECRET_RESPONSE=$(curl --insecure -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
              https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/namespaces/default/secrets/cluster-details-MYSERVER-staging-cp)
              export TARGET_CLUSTER_IP_ADDRESS=$(echo $SECRET_RESPONSE|jq '.data.kubeconfig' | base64 -di | yq e ".clusters[0].cluster.server" -)
              echo $TARGET_CLUSTER_IP_ADDRESS
              export TARGET_PROJECTS=$(curl --insecure -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
              https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/namespaces/argocd/projects)
              echo $TARGET_PROJECTS
      restartPolicy: OnFailure
      dnsPolicy: ClusterFirst
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-reader-sa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: appprojects
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["appprojects", "appprojects.argoproj.io"]
    verbs: ["get", "watch", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reader-crb-crossplane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader-cr
subjects:
  - kind: ServiceAccount
    name: secret-reader-sa
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-reader-crb-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-reader-cr
subjects:
  - kind: ServiceAccount
    name: secret-reader-sa
    namespace: argocd

```
