### ISSUE TITLE
caData is not used when specifying the tlsClientConfig

### ISSUE THREAD

**Issue by r-nasiri** [crossplane-contrib/provider-argocd#192]
### What happened?
I am trying to create a new Cluster that uses AWS AuthConfig. In addition to ClusterName and roleARN for authentication, we also need to configure `tlsClientConfig`. If I set the `insecure=true` everything works but If I set `insecure=false` and add the `caData`, it complains about certificate. I've confirmed that caData being passed is correct. I checked the code and it seems that caData is not passed from input parameters to ArgoCD cluster object.

### How can we reproduce it?
Create a new cluster as below:

```
apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example-cluster
spec:
  forProvider:
    config:
      awsAuthConfig:
           clusterNmae: sample-cluster
           roleARN: arn:aws:iam::xxxxxxxx:role/argocd-cluster-access"
      tlsClientConfig:
        insecure: false
        caData: <base64 encoded ca cert from cluster>
    name: example-cluster
    server: https://kubernetes.default.svc
  providerConfigRef:
    name: argocd-provider
```

### What environment did it happen in?
Crossplane version: 1.16
Crossplane Provider argocd version: 0.9.0

**Comment by jpachcuda** [comment]
Here to confirm I also ran into this issue. I tested creating an identical cluster secret manually and was able to successfully connect to the external cluster from argo.

Also, I deployed a secret and used the caDataSecretRef instead and was able to create the cluster resource. This is a usable workaround until the cluster resource caData field is fixed.

Cluster resource
```yaml
apiVersion: cluster.argocd.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: sample-cluster
spec:
  forProvider:
    config:
      awsAuthConfig:
        clusterName: sample-cluster
        roleARN: arn:aws:iam:: xxxxxxxx:role/argocd-cluster-access
      tlsClientConfig:
        caDataSecretRef:
          key: caData
          name: sample-cluster-cadata
          namespace: crossplane-system
        insecure: false
    labels:
    name: sample-cluster
    server: https://xxxxxxxxxxxxxxxxxxxxxxxxx.sk1.us-east-2.eks.amazonaws.com
  providerConfigRef:
    name: provider-argocd
```

Secret
```yaml
apiVersion: v1
kind: Secret
metadata:
  name:  sample-cluster-cadata
  namespace: crossplane-system
data:
  caData: <base64 encoded secret data>
```
