### ISSUE TITLE
Add SourceNamespaces field to Project MR to be able to use Application in any namespace feature of argocd

### ISSUE THREAD

**Issue by smileisak** [crossplane-contrib/provider-argocd#198]
### What problem are you facing?

sourceNamespaces field is missing in the project configuration of the managed resource. This field should be added to support the use case of deploying applications in any namespace. Example:

```yaml
apiVersion: projects.argocd.crossplane.io/v1alpha1
kind: Project
metadata:
  name: example-project
spec:
  forProvider:
    sourceNamespaces:
      - default
    projectLabels:
      argocd.crossplane.io/global-project: "true"
  providerConfigRef:
    name: argocd-provider
```

### How could Crossplane help solve your problem?

The field should be present in the spec.forProvider.

### References

- [Argocd In any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/)
