### ISSUE TITLE
Unexpectedly high resource usage

### ISSUE THREAD

**Issue by hsharrison** [crossplane-contrib/provider-argocd#22]
### What happened?
I noticed the status of the provider became unhealthy.
Autoscaling kicked in and added a node which solved the issue temporarily.
Checking the GKE console I saw that CPU and memory were increasing.

![image](https://user-images.githubusercontent.com/4441865/170686722-cb52aa62-178a-43be-a271-f470a309a9b3.png)

Nothing in the logs.

### How can we reproduce it?
Could be related to using ArgoCD v2.4.0-rc2+cd5, I wanted to try the `argocd-k8s-auth` feature with GCP (which works fine, a nice solution to #13).

Provider
```
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-argocd
spec:
  package: crossplane/provider-argocd:v0.1.0
```

ProviderConfig
```
apiVersion: argocd.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: argocd-provider
spec:
  serverAddr: REDACTED
  insecure: false
  plainText: false
  credentials:
    source: Secret
    secretRef:
      namespace: argocd
      name: argocd-credentials
      key: authToken
```
Cluster (part of a Composition)
```
  - name: argocd-cluster
    base:
      apiVersion: cluster.argocd.crossplane.io/v1alpha1
      kind: Cluster
      spec:
        providerConfigRef:
          name: argocd-provider
        forProvider:
          config:
            tlsClientConfig:
              insecure: false
              caDataSecretRef:
                key: clusterCA
            execProviderConfig:
              apiVersion: client.authentication.k8s.io/v1beta1
              command: argocd-k8s-auth
              args:
                - gcp

    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.name
    - fromFieldPath: spec.deletionPolicy
      toFieldPath: spec.deletionPolicy
    - fromFieldPath: status.endpoint
      toFieldPath: spec.forProvider.server
      policy:
        fromFieldPath: Required
      transforms:
      - type: string
        string:
          fmt: "https://%s"
    - fromFieldPath: metadata.uid
      toFieldPath: spec.forProvider.config.tlsClientConfig.caDataSecretRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-gkecluster"
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.forProvider.config.tlsClientConfig.caDataSecretRef.namespace

    readinessChecks:
      - type: None
```

There are only two ProviderConfigUsages, two clusters.
One is for the in-cluster so it is not acutally used.
The other is working fine.

### What environment did it happen in?
* Crossplane version: 1.7.0
* Crossplane Provider argocd version: 0.1.0
* Kubernetes version (use `kubectl version`)
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5-gke.2400", GitCommit:"edad26ea7e78d44536b547193f30209b03e954c9", GitTreeState:"clean", BuildDate:"2022-04-15T09:31:56Z", GoVersion:"go1.17.8b7", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes distribution (e.g. Tectonic, GKE, OpenShift): GKE
