### ISSUE TITLE
Project field is acceptable even for Helm-type repositories

### ISSUE THREAD

**Issue by rounakdatta** [crossplane-contrib/provider-argocd#245]
### What happened?
For the field [`spec.forProvider.project`](https://marketplace.upbound.io/providers/crossplane-contrib/provider-argocd/v0.9.2/resources/repositories.argocd.crossplane.io/Repository/v1alpha1),
> Project is a reference to the project with scoped repositories only for git repos

This is incorrect. Helm repositories can also be scoped to projects. If we end up passing `spec.forProvider.project` for a Helm repository, it gets created successfully, but the status never reconciles. We must fix this.

### How can we reproduce it?

```yaml
apiVersion: repositories.argocd.crossplane.io/v1alpha1
kind: Repository
  name: simple-helm-charts
spec:
  forProvider:
    inheritedCreds: true
    insecure: true
    name: Helm Charts
    passwordRef:
      key: password
      name: github-credentials
      namespace: crossplane-system
    project: mydearproject
    repo: https://raw.githubusercontent.com/simple-tech/simple-helm-charts/main/
    type: helm
    username: hellodear
  providerConfigRef:
    name: argo-providerconfig
```

### What environment did it happen in?
Crossplane version: 1.18.0
Crossplane Provider argocd version: v0.9.1
