### ISSUE TITLE
Indeterminstic Uninstall Order results in Stale Resources

### ISSUE THREAD

**Issue by lieberlois** [crossplane-contrib/provider-argocd#254]
### What happened?
I am using the helm + the argo provider to provision vClusters and then register them into Argo. Sometimes when deleting my Claim the Helm Release (including the Kubeconfig Secret of the vCluster) gets deleted before the Argo Cluster resource rather than the "correct order" which would be first deleting/unregistering the Cluster in Argo, then cleaning up the helm resource. Then the Argo resource is stuck in the following state:

```
Status:
  At Provider:
    Connection State:
      Applications Count:  1
      Cache Info:
        Apis Count:            47
        Last Cache Sync Time:  2025-03-15T10:25:06Z
        Resources Count:       232
      Connection State:
        Attempted At:  2025-03-15T10:25:56Z
        Message:
        Status:        Successful
      Server Version:  1.31
    Kubeconfig:
      Secret:
        Resource Version:  32299
  Conditions:
    Last Transition Time:  2025-03-15T10:25:06Z
    Reason:                Available
    Status:                True
    Type:                  Ready
    Last Transition Time:  2025-03-15T10:26:20Z
    Message:               observe failed: cannot get Kubernetes secret: Secret "vcluster-kubeconfig" not found
    Reason:                ReconcileError
    Status:                False
    Type:                  Synced
Events:
  Type     Reason                         Age                     From             Message
  ----     ------                         ----                    ----             -------
  Warning  CannotCreateExternalResource   8m15s (x19 over 8m36s)  managed/cluster  cannot get Kubernetes secret: Secret "vcluster-kubeconfig" not found
  Normal   CreatedExternalResource        7m38s                   managed/cluster  Successfully requested creation of external resource
  Normal   UpdatedExternalResource        7m37s                   managed/cluster  Successfully requested update of external resource
  Warning  CannotObserveExternalResource  53s (x17 over 6m23s)    managed/cluster  cannot get Kubernetes secret: Secret "vcluster-kubeconfig" not found
```

A claim looks like this:
```yaml
apiVersion: idp.lieberlois/v1alpha1
kind: VirtualCluster
metadata:
  name: customer2
spec: {}
```

### How can we reproduce it?

Here is the relevant part of the Crossplane Composition

```yaml
spec:
  compositeTypeRef:
    apiVersion: idp.lieberlois/v1alpha1
    kind: XVirtualCluster
  resources:
  - name: vcluster
    base:
      apiVersion: helm.crossplane.io/v1beta1
      kind: Release
      name: vcluster-test
      spec:
        forProvider:
          chart:
            name: vcluster
            repository: https://charts.loft.sh
            version: 0.23.0
          namespace: vcluster-test
          values:
            controlPlane:
              proxy:
                extraSANs:
                  - vcluster-test.vcluster-test.svc.cluster.local
            exportKubeConfig:
              secret:
                name: vcluster-kubeconfig
              server: https://vcluster-test.vcluster-test.svc.cluster.local
        providerConfigRef:
          name: helm-provider
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-vcluster"
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: metadata.name
        - fromFieldPath: metadata.name
        strategy: string
        string:
          fmt: "https://%s-vcluster.%s.svc.cluster.local"
      toFieldPath: spec.forProvider.values.exportKubeConfig.server
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: metadata.name
        - fromFieldPath: metadata.name
        strategy: string
        string:
          fmt: "%s-vcluster.%s.svc.cluster.local"
      toFieldPath: spec.forProvider.values.controlPlane.proxy.extraSANs[0]
  - name: argo-cluster
    base:
      apiVersion: cluster.argocd.crossplane.io/v1alpha1
      kind: Cluster
      name: vcluster-test
      spec:
        forProvider:
          labels:
            managed-by: crossplane
          config:
            kubeconfigSecretRef:
              key: config
              name: vcluster-kubeconfig
              namespace: vcluster-test
          name: vcluster-test
        providerConfigRef:
          name: argocd-provider
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.config.kubeconfigSecretRef.namespace
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-argo-ref"
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.name
```

### What environment did it happen in?
Crossplane version: latest
Crossplane Provider argocd version: xpkg.upbound.io/crossplane-contrib/provider-argocd:v0.9.2

K8s distribution: kind (local for testing)
Operating System: MacOS
