### ISSUE TITLE
v0.10.0 cannot start with unique name error

### ISSUE THREAD

**Issue by stevendborrelli** [crossplane-contrib/provider-argocd#257]
### What happened?

Crossplane provider v0.10.0 will enter `CrashLoopBackOff` with the following error:

```shell
crossplane-argocd-provider: error: Cannot setup argocd controllers: controller with name managed/project already exists. Controller names must be unique to avoid multiple controllers reporting to the same metric
```

### How can we reproduce it?

Install v0.10.0 on any crossplane cluster:

```yaml
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-argocd
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-argocd:v0.10.0
```

### What environment did it happen in?

Crossplane version:  1.19.0-up.1, 1.18.x-up.1

Crossplane Provider argocd version: v0.10.0
