### ISSUE TITLE
Credential Templates not working

### ISSUE THREAD

**Issue by raweber42** [crossplane-contrib/provider-argocd#277]
### What happened?
I am trying to create argo [credential templates](https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#credential-templates) in order to reduce the amount of `repositories` I need to manually create. However, I cannot see how to make it work with crossplane. I can see that [terraform seems to support this](https://github.com/argoproj-labs/terraform-provider-argocd/issues/181) (not verified though). 

When I create a credential template like this:
```
apiVersion: repositories.argocd.crossplane.io/v1alpha1
kind: Repository
metadata:
  name: example-scoped-project
spec:
  forProvider:
    passwordRef:
      key: token
      name: example-project
      namespace: crossplane-system
    project: example-project
    repo: https://gitlab.com/example-group # No '.git' here, as it refers to a path
    type: git
    username: example-user
  providerConfigRef:
    name: argocd-provider
```

I receive the error:
```
Unable to connect to repository: rpc error: code = Unknown desc = error testing repository connectivity: unable to ls-remote HEAD on repository: failed to list refs: unexpected client error: unexpected requesting "https://gitlab.xxx.io/testteam/info/refs?service=git-upload-pack" status code: 302
```

It looks to me like credential templates are not supported. (also indicated by naming the property `repo`, which implies a git repository and not a `url` as in the [terraform configuration options](https://registry.terraform.io/providers/oboukili/argocd/latest/docs/resources/repository_credentials#url-1).

I am happy to contribute, if needed.

### How can we reproduce it?
Try creating a credential template for a path (don't use `.git` as `repo`)

### What environment did it happen in?
Crossplane version: xpkg.upbound.io/crossplane/crossplane:v1.18.2
Crossplane Provider argocd version: xpkg.upbound.io/crossplane-contrib/provider-argocd:v0.10.1
