### ISSUE TITLE
ProviderConfig doesn't support Filesystem credentials

### ISSUE THREAD

**Issue by cjyar** [crossplane-contrib/provider-argocd#30]
### What happened?

The ProviderConfig for argocd has fields under `spec.credentials` for `env`, `fs`, and `secretRef`; but `fs` isn't supported.

### How can we reproduce it?

```yaml
apiVersion: argocd.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Environment
    fs:
      path: /vault/secret/authToken
  serverAddr: https://argocd.example.com/
```

On apply:
```
The ProviderConfig "default" is invalid: spec.credentials.source: Unsupported value: "Filesystem": supported values: "None", "Secret", "Environment"
```

### What environment did it happen in?
Crossplane version: v1.9.1
Crossplane Provider argocd version: v0.1.0

I think this is just a one-line change at https://github.com/crossplane-contrib/provider-argocd/blob/main/package/crds/argocd.crossplane.io_providerconfigs.yaml#L98, but I wasn't able to get a build environment working in MacOS to actually make a PR.
